{
 "title": "Docker Container",
 "description": "Docker container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_cpu_user_seconds_total, job)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"}, instance)"
   },
   {
    "name": "Prod",
    "label": "Prod",
    "query": "label_values(container_cpu_user_seconds_total{instance=~\"10.115.220.32:8080|10.115.220.33:8080\", name!=\"cadvisor\"}, name)"
   },
   {
    "name": "NonProd",
    "label": "NonProd",
    "query": "label_values(container_cpu_user_seconds_total{instance=~\"10.115.222.21:8080|10.115.222.22:8080\", name!=\"cadvisor\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Contianers",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - (max by(name) (last_over_time(container_last_seen{name!=\"\"}[3m]))) < 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "count(container_last_seen{instance=~\"$node\",image=~\"(.)+\"})",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "count(container_last_seen{instance=~\"$node\",job=~\"$job\",image!=\"\"})",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$node\"}[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Network Traffic on Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$node\",id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"$node\",id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Cached Memory per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$node\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$node\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$node\",name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$node\",name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$node\",name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "cadvisor_version_info{instance=~\"$node\"}",
     "legendFormat": "cAdvisor Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info{}",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info{instance=~\"$node\"}",
     "legendFormat": "Node-Exporter Version: {{version}}"
    },
    {
     "expr": "cadvisor_version_info{instance=~\"$node\"}",
     "legendFormat": "Docker Version: {{dockerVersion}}"
    },
    {
     "expr": "cadvisor_version_info{instance=~\"$node\"}",
     "legendFormat": "Host OS Version: {{osVersion}}"
    },
    {
     "expr": "cadvisor_version_info{instance=~\"$node\"}",
     "legendFormat": "Host Kernel Version: {{kernelVersion}}"
    }
   ]
  }
 ]
}